name: beeping_flutter
description: "Flutter Framework SDK official package."
version: 0.0.0+1
homepage: https://beeping.io

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.

  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  plugin:
    platforms:
      android:
        package: com.example.beeping_flutter
        pluginClass: BeepingFlutterPlugin
      ios:
        pluginClass: BeepingFlutterPlugin

  # To add assets to your plugin package, add an assets section, like this:
  # example:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  
  # To add custom fonts to your plugin package, add a fonts section here.
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
